### ISSUE TITLE
Is this gem being actively maintained?

### ISSUE THREAD

**Issue by kapso** [adzap/validates_timeliness#118]
There has been no new release since August 22, 2012

**Comment by fny** [comment]
@johncarney Can you break out the gem from being a fork? There's currently no way to submit issues, make PRs, or search the code.

**Comment by johncarney** [comment]
I'd be happy to do that, @fny, but I'm not entirely sure how to do it. I'll look into it.

**Comment by fny** [comment]
Apparently you'll need to contact support:
http://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository

**Comment by sobrinho** [comment]
@adzap you are no longer maintaining the gem?

**Comment by penman** [comment]
@johncarney if it helps, you can enable issues for a fork in the repo's settings.

**Comment by adzap** [comment]
Hi All. I know I know. I've been totally AWOL. But, BUT, I am returning to the land of open source and getting this gem back into shape, with all your contributions of course. Thanks for keeping it alive.

**Comment by monkbroc** [comment]
Thanks @adzap!

I'll make a big PR based on @johncarney's fork since that's the one I've been using in production recently.

**Comment by adzap** [comment]
If it's not too much trouble I'd like to avoid a patch bomb. I plan to look over @johncarney's fork and see what I can pull in and what might need some tweaking.

**Comment by monkbroc** [comment]
OK. I'll give you some space so you can get this gem back in shape. Just let me know where you'd like some help.

Two other recent forks to look at are https://github.com/kernel-io/validates_timeliness and https://github.com/appfolio/validates_timeliness

**Comment by adzap** [comment]
I am going to draw a line for this current version for v3.x being Rails 3 compatible only. Then make a v4 for Rails 4 etc. Keep in step with Rails versions.
