### ISSUE TITLE
Why is ignore_restriction_errors different in test env

### ISSUE THREAD

**Issue by hajder** [adzap/validates_timeliness#124]
In initialiser there's following code

    ValidatesTimeliness.ignore_restriction_errors = !Rails.env.test?

which just caused me to scratch my head for ~2 hours. Why is that set differently in test env?

**Comment by jamesottaway** [comment]
:+1: I just spent a few hours scratching my head too.

**Comment by adzap** [comment]
Do you want a failed restriction method or proc to bubble up a full blown exception?

**Comment by adzap** [comment]
In which environment did this cause you the problems?
