### ISSUE TITLE
Using option :format method timeliness_type_cast_code ignores given :format

### ISSUE THREAD

**Issue by phlegx** [adzap/validates_timeliness#125]
Using the following validation:

```ruby
validates :published_at, presence: true, timeliness: { type: :datetime, format: 'dd.mm.yyyy, hh:nn' }
```

The validation returns an error that the attribute must be set. This is caused by the method ```timeliness_type_cast_code(attr_name, var_name)``` in file https://github.com/johncarney/validates_timeliness/blob/master/lib/validates_timeliness/attribute_methods.rb#L65

The ```Timeliness::Parser.parse()``` call ignores the ```:format``` option set in the validation.

```ruby
"#{var_name} = Timeliness::Parser.parse(#{var_name}, :#{type}, :zone => #{timezone.inspect})"
```

**Any idea how t add ```:format``` option dynamically to ```Timeliness::Parser.parse()```?!**

**Comment by phlegx** [comment]
I have solved the problem by adding the following line in the config:

```ruby
ValidatesTimeliness.setup do |config|
  config.use_plugin_parser = true
  config.parser.add_formats(:datetime, 'dd.mm.yyyy, hh:nn')
end
```

**Comment by adzap** [comment]
Yep you got it. Type casting and validation are not the same thing. Typecasting should any valid value. The validation should block the valid acceptance of a value for more specific reasons e.g. in comparison to another value or, in your case a specific format.
