### ISSUE TITLE
Is there syntax to custom validate

### ISSUE THREAD

**Issue by dieuit07** [adzap/validates_timeliness#126]
Example:
```
validates_datetime :public_date, :on_or_after => :release_date
```
Error is not good enough for client understand : 
```
Public date must be on or after 2015-07-01 09:33:00
```
I recommend it should be :) 
```
Public date must be on or after 2015-07-01 09:33:00 (release date)
```

**Comment by adzap** [comment]
You can override any validation message in the locale file per attribute or with the message option key

validates_datetime :public_date, :on_or_after => :release_date, :on_or_after_message => "must be on or after %{restriction} (release date)"

We wouldn't use the symbol as anything such as a name in the message. The symbol could be any method which may not semantically represent the value to the user.
