### ISSUE TITLE
`@timeliness_methods_generated` is not reset properly

### ISSUE THREAD

**Issue by codez** [adzap/validates_timeliness#133]
In `lib/validates_timeliness/orm/active_record.rb#L56`, `@timeliness_methods_generated` should be set to `false` instead of `true`, otherwise the methods will not be regenerated on a subsequent `define_attribute_methods` call.

**Comment by adzap** [comment]
Yes of course. Thought I had already checked that. Oh well, thanks for the report. See 4.0.2.
