### ISSUE TITLE
Not working after update

### ISSUE THREAD

**Issue by kmaiorini82** [adzap/validates_timeliness#134]
I just updated my project to ruby 2.2.1 and rails 3.3.22.  I did a bundle update and bundle install.  Everything went fine.  It shows I am currently, "Using validates_timeliness 4.0.2".  When I go to run my app I am getting the following...

/Users/kjm/.rvm/gems/ruby-2.2.1/gems/validates_timeliness-4.0.2/lib/validates_timeliness/validator.rb:59:in `<class:Validator>': undefined method`version' for ActiveModel:Module (NoMethodError)
    from /Users/kjm/.rvm/gems/ruby-2.2.1/gems/validates_timeliness-4.0.2/lib/validates_timeliness/validator.rb:5:in `<module:ValidatesTimeliness>'
    from /Users/kjm/.rvm/gems/ruby-2.2.1/gems/validates_timeliness-4.0.2/lib/validates_timeliness/validator.rb:4:in`<top (required)>'
    from /Users/kjm/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
    from /Users/kjm/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in`block in require'
    from /Users/kjm/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /Users/kjm/.rvm/gems/ruby-2.2.1/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in`require'
    from /Users/kjm/.rvm/gems/ruby-2.2.1/gems/validates_timeliness-4.0.2/lib/validates_timeliness.rb:66:in `<top (required)>'
    from /Users/kjm/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in`require'
    from /Users/kjm/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    from /Users/kjm/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in`each'
    from /Users/kjm/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
    from /Users/kjm/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in`each'
    from /Users/kjm/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
    from /Users/kjm/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.10.6/lib/bundler.rb:134:in`require'
    from /Users/kjm/Development/alldlax/config/application.rb:7:in `<top (required)>'
    from /Users/kjm/.rvm/gems/ruby-2.2.1/gems/railties-3.2.22/lib/rails/commands.rb:53:in`require'
    from /Users/kjm/.rvm/gems/ruby-2.2.1/gems/railties-3.2.22/lib/rails/commands.rb:53:in `block in <top (required)>'
    from /Users/kjm/.rvm/gems/ruby-2.2.1/gems/railties-3.2.22/lib/rails/commands.rb:50:in`tap'
    from /Users/kjm/.rvm/gems/ruby-2.2.1/gems/railties-3.2.22/lib/rails/commands.rb:50:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'

I am running on Mac OS X El Capitan Version 10.11.2...

uname -a output = Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64

I am sure I am doing something stupid here but can't seem to figure it out!

**Comment by monkbroc** [comment]
Version 4.x only works with Rails 4.x. To keep using validates_timeliness with Rails 3.x use this in your Gemfile:

`gem 'validates_timeliness', '~> 3.0'`
