### ISSUE TITLE
Different behavior when using ActiveRecord as a hash

### ISSUE THREAD

**Issue by gvasselai** [adzap/validates_timeliness#137]
Usage:
`validates_date :dt_from, :dt_to, { allow_nil: true, allow_blank: true }`

```
irb(main):045:0> p.valid?
=> true
irb(main):046:0> p[:dt_to] = nil
=> nil
irb(main):047:0> p.valid?
=> false
irb(main):048:0> p.errors.messages
=> {:dt_to=>["is not a valid date"]}
irb(main):049:0> p.dt_to = nil
=> nil
irb(main):050:0> p.valid?
=> true
```

Expected the validator to behave the same for `p[:dt_to] = nil` and `p.dt_to = nil`.

**Comment by adzap** [comment]
What version of ActiveRecord?

**Comment by gvasselai** [comment]
Hi Adam,

Thank you for your quick response.

My active record / rails version:
/usr/local/lib/ruby/gems/2.0.0/gems/activerecord-4.0.5

Gabriela

Gabriela Vasselai || +554791767812 || gabriela.vasselai (skype) ||
linkedin.com/in/gabrielavasselai

2016-02-27 16:15 GMT-03:00 Adam Meehan <notifications@github.com>:

> What version of ActiveRecord?
>

**Comment by adzap** [comment]
It would be great if you could write a failing spec in the active record orm spec file.

**Comment by adzap** [comment]
thanks @yez

@gvasselai does this spec cover your case? If so, the weird thing is that it passes, so no failure in this case.
