### ISSUE TITLE
Way to hide attribute name from error message?

### ISSUE THREAD

**Issue by manojmj92** [adzap/validates_timeliness#149]
When I try to save an attribute (say, birthday) with invalid date, I get the following validation error on the form

`birthday is not a valid date`.

I need a way to hide the `birthday` part from the error message. Exposing my attribute name doesn't seem fit to me. 
For eg: My database column could be named just `bd` or `birth` or anything and showing `bd is not a valid date` seems inappropriate.

Anyway to do this?

**Comment by titanium-cranium** [comment]
I think if you just add the message after the validation it overrides the default message
e.g. validates_date :birthday,  message => 'Not a valid date'

**Comment by adzap** [comment]
There is no feature in ActiveRecord to remove the attribute name when displaying errors using `full_messages` which is the default for form inputs I believe. You'd need to display the individual error message per attribute.

See [Rails Guides](http://guides.rubyonrails.org/active_record_validations.html#working-with-validation-errors)

**Comment by aquellier** [comment]
Hey I have the same problem,
I've checked the rails guide but couldn't find my answer. 

Usually I would define a custom method with sth like this 
`errors.add(:base, 'You must be at least 18 years old')`
but I don't know how to do it here. 

Is there any way to do the same with the gem?

**Comment by adzap** [comment]
Does any other field you are validating that is not a datetime show the error message in a different way?
