### ISSUE TITLE
Date of birth is not a valid date each time setting the date properly

### ISSUE THREAD

**Issue by anjolovic** [adzap/validates_timeliness#158]
Hi 

I am trying to validate date_of_birth using the following code: 
```
validates_date :date_of_birth, :before => lambda { 18.years.ago },
                         :before_message => "must be at least 18 years old"
```
In my form, I have the following:
```
<%= form.text_field :date_of_birth, type: 'date', id: :profile_data_of_birth %>
```
Standard. Nothing particuler. But when I set the date, I keep getting the following error:

```
Date of birth is not a valid date
```
Any thoughts why this is happening?

Thanks very much!

**Comment by adzap** [comment]
what format is the DOB your inputting?
