### ISSUE TITLE
`value(object)` method fails in Rails 5.2

### ISSUE THREAD

**Issue by AquisTech** [adzap/validates_timeliness#170]
`value(object)` method fails in Rails 5.2

**Details**
In Rails 5.2 value method does not accept any parameter.
It fails with
```
ActionView::Template::Error (wrong number of arguments (given 0, expected 1)):
```

**Reference**
https://github.com/rails/rails/commit/530b5fea8f3e04c45a20ff3dcc8d473a6d25c1b4

**Solution**
There can be 2 possible alternatives
_Option 1:_
Keep only `value` method definition without parameters considering support to the latest version or release 2 different versions of gems mentioning Rails < 5.2 and Rails > 5.2 dependencies
_Option 2:_
Write 2 methods with some condition like 
```
if Rails.version.to_f < 5.2
  def value(object)
  end
else
  def value
  end
end
```

**Comment by AquisTech** [comment]
I have done changes following the second approach.
Please review PR #171 and merge it

**Comment by adzap** [comment]
Option 1 is a no go. 

Option 2 is the fallback. 

But there is another way which should work though a little less transparent. I will a commit which you can test.
