### ISSUE TITLE
[Request] Publish Version 5.0.0.pre to Ruby Gems 

### ISSUE THREAD

**Issue by cdesch** [adzap/validates_timeliness#176]
Can you please publish `5.0.0.pre` to RubyGems? [validates_timeliness on RubyGems.org](https://rubygems.org/gems/validates_timeliness) does not appear to be published.

It would be nice to publish this version to align with the README.md.

```
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/..
Could not find gem 'validates_timeliness (~> 5.0.0.pre)' in any of the gem
sources listed in your Gemfile.

Process finished with exit code 7
```

or please create a tag for it, eg:

    gem 'validates_timeliness', github: 'adzap/validates_timeliness', tag: '5.0.0.pre'

**Comment by adzap** [comment]
Yes will do, sorry.

I will publish an alpha actually.

**Comment by maurosbu** [comment]
@adzap will the alpha be compatible with Rails 5.2?

**Comment by adzap** [comment]
v5.0.0.alpha1 released

**Comment by adzap** [comment]
@maurosbu It passes the Rails 5.2 build but it will need testing

**Comment by cdesch** [comment]
@adzap thank you!
