### ISSUE TITLE
cannot load such file -- validates_timeliness/helper_methods (LoadError)

### ISSUE THREAD

**Issue by maurosbu** [adzap/validates_timeliness#177]
Hi, I'm using **Rails 5.2.0** and  **validates_timeliness 5.0.0.alpha1** 

This is the error I get in production:

    activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require': cannot load such file -- validates_timeliness/helper_methods (LoadError)

It works if I add the following in the Gemfile:

    gem 'validates_timeliness', github: 'adzap/validates_timeliness'

Can you please publish a new version fixing the issue?

Many thanks,
Mauro

**Comment by adzap** [comment]
Can you please give me the reset of that backtrace?

**Comment by maurosbu** [comment]
@adzap hope the following can help.

    Traceback (most recent call last):
        23: from bin/rails:9:in `<main>'
        22: from bin/rails:9:in `require'
        21: from /var/www/demo/shared/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<top (required)>'
        20: from /var/www/demo/shared/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/command.rb:46:in `invoke'
        19: from /var/www/demo/shared/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/command/base.rb:65:in `perform'
        18: from /var/www/demo/shared/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        17: from /var/www/demo/shared/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        16: from /var/www/demo/shared/bundle/ruby/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        15: from /var/www/demo/shared/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/commands/console/console_command.rb:95:in `perform'
        14: from /var/www/demo/shared/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/command/actions.rb:17:in `require_application_and_environment!'
        13: from /var/www/demo/shared/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/command/actions.rb:17:in `require'
        12: from /var/www/demo/releases/20180615120012/config/application.rb:18:in `<top (required)>'
        11: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler.rb:114:in `require'
        10: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:65:in `require'
         9: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:65:in `each'
         8: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:76:in `block in require'
         7: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:76:in `each'
         6: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:81:in `block (2 levels) in require'
         5: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:81:in `require'
         4: from /var/www/demo/shared/bundle/ruby/2.5.0/gems/validates_timeliness-5.0.0.alpha1/lib/validates_timeliness.rb:67:in `<top (required)>'
         3: from /var/www/demo/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
         2: from /var/www/demo/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
         1: from /var/www/demo/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
    /var/www/demo/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require': cannot load such file -- validates_timeliness/helper_methods (LoadError)

L18 of /var/www/demo/releases/20180615120012/config/application.rb:18

    Bundler.require(*Rails.groups)

**Comment by adzap** [comment]
Thanks but I am no clearer on what the issue is. I setup a test 5.2 app and added the current version of the gem and started the server and a rails console and didn't get the error.

The file is in gem, so I don't have any suggest work around either.

**Comment by maurosbu** [comment]
@adzap version 5.0.0.alpha1 works in development environment! The problem appears in production.

**Comment by maurosbu** [comment]
@adzap same issue with 5.0.0.alpha2 in production.

**Comment by adzap** [comment]
Still can't replicate this. I am not using in production yet, but I spun it up locally with prod settings i.e caching classes, eager load etc. and got no error.

**Comment by bboe** [comment]
I had the same problem. The issue pertains to file permissions:

```
$ tar -xOf validates_timeliness-5.0.0.alpha2.gem data.tar.gz | tar -tvzf - | grep -v -- -rw-r--r--
-rw-------  0 wheel  wheel    1060 Jul  2 04:13 LICENSE
-rw-------  0 wheel  wheel     665 Jul  2 04:13 Rakefile
-rw-------  0 wheel  wheel      31 Jul  2 04:13 init.rb
-rw-------  0 wheel  wheel     472 Jul  2 04:13 lib/generators/validates_timeliness/install_generator.rb
-rw-------  0 wheel  wheel     538 Jul  2 04:13 lib/generators/validates_timeliness/templates/en.yml
-rw-------  0 wheel  wheel    1419 Jul  2 04:13 lib/generators/validates_timeliness/templates/validates_timeliness.rb
-rw-------  0 wheel  wheel     713 Jul  2 04:13 lib/validates_timeliness/helper_methods.rb
-rw-------  0 wheel  wheel     580 Jul  2 04:13 lib/validates_timeliness/railtie.rb
-rw-------  0 wheel  wheel    1249 Jul  2 04:13 spec/support/config_helper.rb
-rw-------  0 wheel  wheel     727 Jul  2 04:13 spec/support/model_helpers.rb
-rw-------  0 wheel  wheel     624 Jul  2 04:13 spec/support/tag_matcher.rb
-rw-------  0 wheel  wheel    6563 Jul  2 04:13 spec/validates_timeliness/extensions/date_time_select_spec.rb
-rw-------  0 wheel  wheel    1571 Jul  2 04:13 spec/validates_timeliness/extensions/multiparameter_handler_spec.rb
-rw-------  0 wheel  wheel     867 Jul  2 04:13 spec/validates_timeliness/helper_methods_spec.rb
-rw-------  0 wheel  wheel    1927 Jul  2 04:13 spec/validates_timeliness/validator/after_spec.rb
-rw-------  0 wheel  wheel    1935 Jul  2 04:13 spec/validates_timeliness/validator/before_spec.rb
-rw-------  0 wheel  wheel    1978 Jul  2 04:13 spec/validates_timeliness/validator/is_at_spec.rb
-rw-------  0 wheel  wheel    1858 Jul  2 04:13 spec/validates_timeliness/validator/on_or_after_spec.rb
-rw-------  0 wheel  wheel    1869 Jul  2 04:13 spec/validates_timeliness/validator/on_or_before_spec.rb
-rw-------  0 wheel  wheel    1452 Jul  2 04:13 spec/validates_timeliness_spec.rb
```

Rubygems unfortunately respects the permissions of the file at the time the gem was built so if you are in a dual-user production mode, no-one but the installing user can access the the files listed above.

It appears that the files in the repository have the correct permissions, but somehow @adzap the ones in the gem you built do not. Could you look into the permissions and release a new version with the permissions set to 644 for all those files?

**Comment by adzap** [comment]
Great catch thanks @bboe. That is strange. Pretty sure nothing had changed in my repo so those permissions may have been like that for a while. Perhaps the bundler rake task used to force permissions but doesn't anymore.

Uploaded alpha3

**Comment by bboe** [comment]
Thanks for the prompt fix @adzap!

**Comment by maurosbu** [comment]
@adzap many thanks, it works!
