### ISSUE TITLE
Useless code in initializer file created by Installation guide

### ISSUE THREAD

**Issue by kamille-gz** [adzap/validates_timeliness#184]
Hi there.

I think the [Installation](https://github.com/adzap/validates_timeliness#installation) on README.md provides us with useless code.

When execute `bundle exec rails generate validates_timeliness:install`, initializer file is created. The file includes `config.extend_orms = [ :active_record ]`.
This code in initializer file is useless because if this gem is installed in Rails applications, ActiveRecord is also installed, that means ActiveRecord will be extended by this gem due to [railtie code](https://github.com/adzap/validates_timeliness/blob/master/lib/validates_timeliness/railtie.rb#L4).

I'm not sure above opinion hundred percent, so let me know your opinion. 🙇

**Comment by kamille-gz** [comment]
BTW, my application that installed this gem does not have [initializer file](https://github.com/adzap/validates_timeliness/blob/master/lib/generators/validates_timeliness/templates/validates_timeliness.rb) is working without any errors.

**Comment by adzap** [comment]
True is not needed when run in a Rails app with ActiveRecord loaded. Can probably just comment it out.
