### ISSUE TITLE
Plans to release a official 6.x version

### ISSUE THREAD

**Issue by pedrofurtado** [adzap/validates_timeliness#199]
Hi @adzap ! 👋 

Thanks for your work on this awesome gem. Is there any plans to release a official 6.x version?

We are using from a very long time the 6.0.0.alpha1, I think it is stable enough to release it as official 👍 

c/c: @marciojg @willradi @leonardocomar

**Comment by dgilperez** [comment]
I'd love to see this as well

**Comment by marciojg** [comment]
Hi @pedrofurtado  Can this problem be closed? I think it's right now. =D

#### https://github.com/adzap/validates_timeliness/blob/master/validates_timeliness.gemspec
`s.add_runtime_dependency("activemodel", [">= 6.0.0", "< 7"])`

**Comment by pedrofurtado** [comment]
Thanks, @marciojg ! 🤝 The latest beta version (6.0.0.beta 2) already constains this change 🎉
