### ISSUE TITLE
ArgumentError: wrong number of arguments (given 3, expected 1..2) on records.error.add

### ISSUE THREAD

**Issue by JigmeT123** [adzap/validates_timeliness#209]
There seems to be an issue in the gem. When trying to add error to the record it gives the error -

`ArgumentError: wrong number of arguments (given 3, expected 1..2)`

the error is coming from the file `lib/validates_timeiness/validator.rb`

```
module ValidatesTimeliness
  class Validator < ActiveModel::EachValidator
    def add_error(record, attr_name, message, value=nil)
      value = format_error_value(value) if value
      message_options = { message: options.fetch(:"#{message}_message", options[:message]), restriction: value }
      record.errors.add(attr_name, message, message_options)
    end
  end
end
```

But this works if I use splat operator
`record.errors.add(attr_name, message, message_options)`

The issue was caused after I updated the gemfile.

**Comment by adzap** [comment]
What version of the gem are you using?
What version of Rails/Activetecord?
What version of Ruby?

**Comment by JigmeT123** [comment]
> What version of the gem are you using? What version of Rails/Activetecord? What version of Ruby?
> […](#)
> On 7 Dec 2021, 5:36 PM +1100, Jigme Tashi Namgyal ***@***.***>, wrote: There seems to be an issue in the gem. When trying to add error to the record it gives the error - ArgumentError: wrong number of arguments (given 3, expected 1..2) the error is coming from the file lib/validates_timeiness/validator.rb module ValidatesTimeliness class Validator < ActiveModel::EachValidator def add_error(record, attr_name, message, value=nil) value = format_error_value(value) if value message_options = { message: options.fetch(:"#{message}_message", options[:message]), restriction: value } record.errors.add(attr_name, message, message_options) end end end But this works if I use splat operator record.errors.add(attr_name, message, message_options) The issue was caused after I updated the gemfile. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Ruby version `ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [arm64-darwin20]`
Rails version `Rails 6.1.4.1`
validates_timeliness version `6.0.0.alpha1`

**Comment by adzap** [comment]
Try the beta1 version of the gem.

**Comment by JigmeT123** [comment]
> Try the beta1 version of the gem.
> […](#)
> On 7 Dec 2021, 5:50 PM +1100, Jigme Tashi Namgyal ***@***.***>, wrote: > What version of the gem are you using? What version of Rails/Activetecord? What version of Ruby? > … > On 7 Dec 2021, 5:36 PM +1100, Jigme Tashi Namgyal @.***>, wrote: There seems to be an issue in the gem. When trying to add error to the record it gives the error - ArgumentError: wrong number of arguments (given 3, expected 1..2) the error is coming from the file lib/validates_timeiness/validator.rb module ValidatesTimeliness class Validator < ActiveModel::EachValidator def add_error(record, attr_name, message, value=nil) value = format_error_value(value) if value message_options = { message: options.fetch(:"#{message}_message", options[:message]), restriction: value } record.errors.add(attr_name, message, message_options) end end end But this works if I use splat operator record.errors.add(attr_name, message, message_options) The issue was caused after I updated the gemfile. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Ruby version ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [arm64-darwin20] Rails version Rails 6.1.4.1 validates_timeliness version 6.0.0.alpha1 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

The error seems to be from beta1. alpha works fine for me

**Comment by JigmeT123** [comment]
The error seems to be from beta1. alpha works fine for me

**Comment by adzap** [comment]
That’s confusing as you just said you were using alpha1 with this error.

**Comment by JigmeT123** [comment]
Yeapp made a mistake. Edited the comment again. The error is from beta

**Comment by JigmeT123** [comment]
Worked Thank you

**Comment by champion-dolphin** [comment]
beta2 works!
