### ISSUE TITLE
Locale for Vietnamese

### ISSUE THREAD

**Issue by tvziet** [adzap/validates_timeliness#216]
I want to add the `vi.yml` file for Vietnamese.

**Comment by pedrofurtado** [comment]
Hey @tvziet! 👋  I suggest for you to add, opening a PR for this gem, what do you think? 
https://github.com/pedrofurtado/timeliness-i18n

The purpose of the gem is to provide translations for timeliness 🤝

**Comment by tvziet** [comment]
Yes, of course. I have created a PR for this requirement. Please review it @pedrofurtado 😀. Thank you for your reply.

https://github.com/pedrofurtado/timeliness-i18n/pull/14

**Comment by rickychilcott** [comment]
The PR has been merged, so this issue can be closed.
