### ISSUE TITLE
Rails 7 Deprecation Warnings

### ISSUE THREAD

**Issue by marclennox** [adzap/validates_timeliness#217]
Rails 7 has deprecated `ActiveRecord::Base.default_timezone` in favor of `ActiveRecord.default_timezone`.  The railtie for this gem is referencing the deprecated method and generates a warning.  Happy to push a merge request if that will help.

```
DEPRECATION WARNING: ActiveRecord::Base.default_timezone is deprecated and will be removed in Rails 7.1.
Use `ActiveRecord.default_timezone` instead.
```

**Comment by foucist** [comment]
Fixed in #213  .. for now I'm using

     gem 'validates_timeliness', '~> 6.0.0.beta2', github: "mitsuru/validates_timeliness", branch: "rails7"

**Comment by h0jeZvgoxFepBQ2C** [comment]
When will the new version be released? Still the beta out there

**Comment by braintrustalex** [comment]
+1

**Comment by zeptoon** [comment]
thanks for costing me tons of time for nothing... #*#$!&#
