### ISSUE TITLE
Support for Rails 7

### ISSUE THREAD

**Issue by jarl-dk** [adzap/validates_timeliness#227]
It seems that it does not work with Rails 7.
Please support Rails 7

**Comment by jarl-dk** [comment]
I see that rails7 is supported in version `7.0.0.beta1` which is hopefully soon released.

**Comment by adzap** [comment]
You should try it and see if it works and then let me know. That would be helpful.

**Comment by jarl-dk** [comment]
Version 7.0.0.beta1 seem to work. Thanks.

**Comment by tagliala** [comment]
I think this can be closed
