### ISSUE TITLE
Comparison to ComparisonValidator

### ISSUE THREAD

**Issue by espen** [adzap/validates_timeliness#233]
Will this gem still be relevant after Rails 7.1? ComparisonValidator will make it possible to do the core features of this gem. While validates_timeliness is excellent I am wondering if there is any reason to use it after this new Rails feature? 

https://github.com/rails/rails/pull/40095

**Comment by espen** [comment]
https://blog.kiprosh.com/rails7-activerecord-comparison-validator/

**Comment by adzap** [comment]
I guess I’ll be out of job.

**Comment by tagliala** [comment]
I've eventually moved to the built-in comparison validator

Relevant changes:

https://github.com/diowa/icare/commit/dd4a4677ab8b0f9aaf8fdcc2e3a05877480efb8d#diff-8f06df7d19040b42d0ab94249895f10fac375834ce5a6f4e55b93570b9dd7d8fL26-R27

Thanks for all these years!
