### ISSUE TITLE
Obsolete?

### ISSUE THREAD

**Issue by arjan0307** [adzap/validates_timeliness#245]
Isn't this gem kind of obsolete since the addition of the comparison validator in Rails 7?

https://guides.rubyonrails.org/v7.0/active_record_validations.html#comparison

**Comment by balakirevs** [comment]
looks like obsolete, managed to replace everything related to this gem with active_record_validations comparison

**Comment by espen** [comment]
Also see https://github.com/adzap/validates_timeliness/issues/233

This gem offers better international support by using `timeliness` as a parser. See https://github.com/adzap/validates_timeliness?tab=readme-ov-file#plugin-parser

**Comment by hoshy** [comment]
@adzap can you help us here?

**Comment by adzap** [comment]
It's up to you all to decide if the gem is useful.
