### ISSUE TITLE
rails 8 support

### ISSUE THREAD

**Issue by balakirevs** [adzap/validates_timeliness#247]
Could not find compatible versions

Because validates_timeliness >= 7.0.0.beta1 depends on activemodel >= 7.0.0, < 8
  and rails >= 8.0.0 depends on activemodel = 8.0.0,
  validates_timeliness >= 7.0.0.beta1 is incompatible with rails >= 8.0.0.
So, because Gemfile depends on rails ~> 8.0.0
  and Gemfile depends on validates_timeliness ~> 7.0.0.beta2,
  version solving has failed.

**Comment by balakirevs** [comment]
Resolves https://github.com/adzap/validates_timeliness/pull/248

@adzap pls check asap

**Comment by lomefin** [comment]
The discussion going on [here](https://github.com/adzap/validates_timeliness/issues/233) means that probably there will be no further upgrade to this gem.

**Comment by espen** [comment]
Does it? This gem does provide functionality that does not exist in Rails. See https://github.com/adzap/validates_timeliness/issues/245#issuecomment-2488256502
