### ISSUE TITLE
US date format mm/dd/yyyy is not working...

### ISSUE THREAD

**Issue by murtyk** [adzap/validates_timeliness#78]
First I tried with the default config. It accepts "April 30,2012" but not "04/30/2012".

Next I tried with config.use_plugin_parser = true but the same problem persists.

My understanding is that the default is US date format but it is not working for me.

Appreciate any help in getting US date formats working.

**Comment by MaffooClock** [comment]
It doesn't appear to be.  I experienced precisely the same problem (and workaround) as @jmif.
