### ISSUE TITLE
3.0.13 and 3.0.14 accepts invalid formats.

### ISSUE THREAD

**Issue by jarl-dk** [adzap/validates_timeliness#85]
I am having a vadliation like this

    validates_time(column_name, :allow_nil => true, :format => 'hh:nn:ss')

Up until 3.0.12 it works fine, but from 3.0.13 and forward it suddenly started to accept values such as "13:54" (without the seconds) That is not what I expect when specifying `:format => 'hh:nn:ss'`

**Comment by adzap** [comment]
I will close this since the gem in not going to explicitly activerecord-tableless. If you like you can explore this by creating your own separate ORM gem (eg. validates_timeliness-activerecord-tabless)
