### ISSUE TITLE
Mongoid and before_type_cast

### ISSUE THREAD

**Issue by Exoth** [adzap/validates_timeliness#97]
Is there any reason why timeliness before_type_cast'ing is applied for ActiveRecord, but not applied to Mongoid? Mongoid supports before_type_cast methods.

So if I change this in ValidatesTimeliness:

        def timeliness_validation_for(attr_names, type)
          super
          attr_names.each { |attr_name| define_timeliness_write_method(attr_name) }
        end

on this:

        def timeliness_validation_for(attr_names, type)
          super
          attr_names.each { |attr_name| define_attribute_timeliness_methods(attr_name, true) }
        end

Everything works perfect. Otherwise Mongoid before_type_casting is getting broken when config.use_plugin_parser = true

**Comment by adzap** [comment]
@Exoth I have merged a Mongoid 3 compatibility PR (no gem release yet). Can you test please.

**Comment by Exoth** [comment]
Not using Mongoid for a long time already, so it would be nice if someone more involved tests it out thoroughly. So as far as I remember, the problem was that before_type_cast holds values, already parsed by Timeliness (has to hold original values instead) - this is what has to be checked.

**Comment by adzap** [comment]
Released version 4 for Rails 4.x. I have extracted mongoid into https://github.com/adzap/validates_timeliness-mongoid but have not released gem or even attempted to get it to work. The repo needs an owner to move it forward.
